defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
      author: Team CoFH
      author_url: http://www.twitter.com/TeamCoFH
  - scope:
      path: "docs"
      type: pages
    values:
      layout: docs
  - scope:
      path: "docs/redstone-flux"
    values:
      nav: redstone-flux
  - scope:
      path: "docs/1.16/thermal-series"
    values:
      nav: thermal-series    
  - scope:
      path: "docs/1.16/archers-paradox"
    values:
      nav: archers-paradox    
  - scope:
      path: "docs/1.15/cofh-core"
    values:
      nav: cofh-core-1.15
  - scope:
      path: "docs/1.12/cofh-core"
    values:
      nav: cofh-core-1.12
  - scope:
      path: "docs/1.12/cofh-world"
    values:
      nav: cofh-world-1.12
  - scope:
      path: "docs/1.12/thermal-foundation"
    values:
      nav: thermal-foundation-1.12
  - scope:
      path: "docs/1.12/thermal-expansion"
    values:
      nav: thermal-expansion-1.12
  - scope:
      path: "docs/1.12/thermal-dynamics"
    values:
      nav: thermal-dynamics-1.12
  - scope:
      path: "docs/1.12/thermal-cultivation"
    values:
      nav: thermal-cultivation-1.12
  - scope:
      path: "docs/1.12/thermal-innovation"
    values:
      nav: thermal-innovation-1.12
  - scope:
      path: "docs/1.12/redstone-arsenal"
    values:
      nav: redstone-arsenal-1.12
  - scope:
      path: "docs/1.12/vanillaplus-tools"
    values:
      nav: vanillaplus-tools-1.12
  - scope:
      path: "docs/1.12/vanillaplus-satchels"
    values:
      nav: vanillaplus-satchels-1.12

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _scripts
  - _modrepos
  - .env
  - /*.pdn
  - /*.xcf
  - /Thumbs.db
  - /.unused

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

permalink: '/posts/:year/:month/:day/:title/'
paginate: 5
paginate_path: "/posts/page-:num/"
url: 'https://teamcofh.com'
