defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      is_post: true

exclude:
  - README.md

permalink: '/posts/:year/:month/:day/:title.html'
