defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
      author: Team CoFH
      author_url: http://www.twitter.com/TeamCoFH
  - scope:
      path: "docs"
      type: pages
    values:
      layout: docs

exclude:
  - README.md
  - _scripts
  - _modrepos
  - /*.pdn
  - /*.xcf
  - /Thumbs.db
  - /.unused

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

permalink: '/posts/:year/:month/:day/:title/'
paginate: 5
paginate_path: "/posts/page-:num/"
url: 'https://teamcofh.com'
