defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
  - scope:
      path: "docs"
      type: pages
    values:
      layout: docs
  - scope:
      path: "docs/cofh-core"
      type: pages
    values:
      nav: cofh-core
  - scope:
      path: "docs/thermal-foundation"
      type: pages
    values:
      nav: thermal-foundation
  - scope:
      path: "docs/thermal-expansion"
      type: pages
    values:
      nav: thermal-expansion
  - scope:
      path: "docs/thermal-dynamics"
      type: pages
    values:
      nav: thermal-dynamics
  - scope:
      path: "docs/redstone-arsenal"
      type: pages
    values:
      nav: redstone-arsenal

exclude:
  - README.md

permalink: '/posts/:year/:month/:day/:title.html'
paginate: 5
paginate_path: "/posts/page-:num/"
