defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
  - scope:
      path: "docs"
      type: pages
    values:
      layout: docs
  - scope:
      path: "docs/cofh-core"
      type: pages
    values:
      nav: cofh-core

exclude:
  - README.md

permalink: '/posts/:year/:month/:day/:title.html'
paginate: 5
paginate_path: "/posts/page-:num/"
