defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
      author: Team CoFH
      author_url: http://www.twitter.com/TeamCoFH
  - scope:
      path: "docs"
      type: pages
    values:
      layout: docs
  - scope:
      path: "docs/redstone-flux"
      type: pages
    values:
      nav: redstone-flux
      mod: Redstone Flux
  - scope:
      path: "docs/cofh-core"
      type: pages
    values:
      nav: cofh-core
      mod: CoFH Core
  - scope:
      path: "docs/cofh-world"
      type: pages
    values:
      nav: cofh-world
      mod: CoFH World
  - scope:
      path: "docs/thermal-foundation"
      type: pages
    values:
      nav: thermal-foundation
      mod: Thermal Foundation
  - scope:
      path: "docs/thermal-expansion"
      type: pages
    values:
      nav: thermal-expansion
      mod: Thermal Expansion
  - scope:
      path: "docs/thermal-dynamics"
      type: pages
    values:
      nav: thermal-dynamics
      mod: Thermal Dynamics
  - scope:
      path: "docs/thermal-cultivation"
      type: pages
    values:
      nav: thermal-cultivation
      mod: Thermal Cultivation
  - scope:
      path: "docs/redstone-arsenal"
      type: pages
    values:
      nav: redstone-arsenal
      mod: Redstone Arsenal
  - scope:
      path: "docs/minefactory-reloaded"
      type: pages
    values:
      nav: minefactory-reloaded
      mod: MineFactory Reloaded
  - scope:
      path: "docs/nether-ores"
      type: pages
    values:
      nav: nether-ores
      mod: Nether Ores


exclude:
  - README.md
  - /*.pdn
  - /*.xcf
  - /Thumbs.db
  - /.unused

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

permalink: '/posts/:year/:month/:day/:title/'
paginate: 5
paginate_path: "/posts/page-:num/"
url: 'http://teamcofh.com'
