title: Team CoFH

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _scripts
  - _modrepos
  - .env
  - /*.pdn
  - /*.xcf
  - /Thumbs.db
  - /.unused

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

permalink: '/blog/:year/:month/:day/:title/'
paginate: 5
paginate_path: "/blog/page-:num/"
url: 'https://teamcofh.com'

defaults:
- scope:
    path: ""
  values:
    layout: default
- scope:
    path: ""
    type: posts
  values:
    is_post: true
    layout: post
    author: Team CoFH
    author_url: http://www.twitter.com/TeamCoFH
- scope:
    path: "docs"
    type: pages
  values:
    layout: docs
    cycle-image: true
    show-image: true
- scope:
    path: "docs/1.7"
    type: pages
  values:
    version: 1.7
- scope:
    path: "docs/1.12"
    type: pages
  values:
    version: 1.12
- scope:
    path: "docs/1.15"
    type: pages
  values:
    version: 1.15
- scope:
    path: "docs/1.16"
    type: pages
  values:
    version: 1.16
- scope:
    path: "docs/*/cofh-core"
    type: pages
  values:
    mod: CoFH Core
- scope:
    path: "docs/*/cofh-world"
    type: pages
  values:
    mod: CoFH World
- scope:
    path: "docs/*/redstone-arsenal"
    type: pages
  values:
    mod: Redstone Arsenal
- scope:
    path: "docs/*/vanilla-satchels"
    type: pages
  values:
    mod: Vanilla+ Satchels
- scope:
    path: "docs/*/vanilla-tools"
    type: pages
  values:
    mod: Vanilla+ Tools
- scope:
    path: "docs/*/ensorcellation"
    type: pages
  values:
    mod: Ensorcellation
- scope:
    path: "docs/*/archer-s-paradox"
    type: pages
  values:
    mod: Archer's Paradox
- scope:
    path: "docs/*/dyenamics"
    type: pages
  values:
    mod: Dyenamics
- scope:
    path: "docs/*/thermal-foundation"
    type: pages
  values:
    mod: Thermal Foundation
- scope:
    path: "docs/*/thermal-expansion"
    type: pages
  values:
    mod: Thermal Expansion
- scope:
    path: "docs/*/thermal-dynamics"
    type: pages
  values:
    mod: Thermal Dynamics
- scope:
    path: "docs/*/thermal-innovation"
    type: pages
  values:
    mod: Thermal Innovation
- scope:
    path: "docs/*/thermal-cultivation"
    type: pages
  values:
    mod: Thermal Cultivation
- scope:
    path: "docs/*/thermal-locomotion"
    type: pages
  values:
    mod: Thermal Locomotion
