defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post

exclude:
  - README.md

permalink: '/posts/:year/:month/:day/:title.html'
paginate: 5
paginate_path: "/posts/page-:num/"
