baseURL: https://teamcofh.com
disablePathToLower: true
languageCode: en-us
title: Team CoFH

assetDir: /static

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  mod: mods
  version: version

permalinks:
  /: /:sections/:filename/
  docs: /:sections/:filename/
  blog: /:sections/:year/:month/:day/:title/

params:
  mc_wiki: https://minecraft.fandom.com/wiki/
  
markup:
  tableOfContents:
    ordered: true